export const JavaDocUrl = 'https://papermc.io/javadocs/paper/1.16/'
export const AllClassesNoFrame = 'allclasses-noframe.html'
export const EventsYaml = 'events.yaml'
export const OutputTemplateFileName = 'README-template.md'
export const OutputFileName = 'README.md'